class_name Pipeline

# Enumerates all component types in Haystack docs
enum ComponentType { 
	LocalWhisperTranscriber,
	RemoteWhisperTranscriber,
	AnswerBuilder,
	PromptBuilder,
	ChatPromptBuilder,
	DynamicPromptBuilder,
	DynamicChatPromptBuilder,
	CacheChecker,
	DocumentLanguageClassifier,
	TransformersZeroShotDocumentClassifier,
	JinaReaderConnector,
	LangfuseConnector,
	OpenAPIServiceConnector,
	AzureOCRDocumentConverter,
	CSVToDocument,
	DOCXToDocument,
	HTMLToDocument,
	JSONConverter,
	MarkdownToDocument,
	OpenAPIServiceToFunctions,
	OutputAdapter,
	PDFMinerToDocument,
	PPTXToDocument,
	PyPDFToDocument,
	TikaDocumentConverter,
	TextFileToDocument,
	UnstructuredFileConverter,
	XLSXToDocument,
	AmazonBedrockTextEmbedder,
	AmazonBedrockDocumentEmbedder,
	AzureOpenAITextEmbedder,
	AzureOpenAIDocumentEmbedder,
	CohereTextEmbedder,
	CohereDocumentEmbedder,
	FastembedTextEmbedder,
	FastembedDocumentEmbedder,
	FastembedSparseTextEmbedder,
	FastembedSparseDocumentEmbedder,
	HuggingFaceAPIDocumentEmbedder,
	HuggingFaceAPITextEmbedder,
	JinaTextEmbedder,
	JinaDocumentEmbedder,
	MistralTextEmbedder,
	MistralDocumentEmbedder,
	NvidiaTextEmbedder,
	NvidiaDocumentEmbedder,
	OllamaTextEmbedder,
	OllamaDocumentEmbedder,
	OpenAIDocumentEmbedder,
	OpenAITextEmbedder,
	OptimumTextEmbedder,
	OptimumDocumentEmbedder,
	SentenceTransformersTextEmbedder,
	SentenceTransformersDocumentEmbedder,
	AnswerExactMatchEvaluator,
	ContextRelevanceEvaluator,
	DeepEvalEvaluator,
	DocumentMAPEvaluator,
	DocumentMRREvaluator,
	DocumentNDCGEvaluator,
	DocumentRecallEvaluator,
	FaithfulnessEvaluator,
	LLMEvaluator,
	RagasEvaluator,
	SASEvaluator,
	NamedEntityExtractor,
	LinkContentFetcher,
	AmazonBedrockChatGenerator,
	AmazonBedrockGenerator,
	AnthropicChatGenerator,
	AnthropicVertexChatGenerator,
	AnthropicGenerator,
	AzureOpenAIChatGenerator,
	AzureOpenAIGenerator,
	CohereChatGenerator,
	CohereGenerator,
	GoogleAIGeminiChatGenerator,
	GoogleAIGeminiGenerator,
	HuggingFaceAPIChatGenerator,
	HuggingFaceAPIGenerator,
	HuggingFaceLocalChatGenerator,
	HuggingFaceLocalGenerator,
	LlamaCppChatGenerator,
	LlamaCppGenerator,
	MistralChatGenerator,
	NvidiaGenerator,
	OllamaChatGenerator,
	OllamaGenerator,
	OpenAIChatGenerator,
	OpenAIGenerator,
	SagemakerGenerator,
	VertexAICodeGenerator,
	VertexAIGeminiChatGenerator,
	VertexAIGeminiGenerator,
	VertexAIImageCaptioner,
	VertexAIImageGenerator,
	VertexAIImageQA,
	VertexAITextGenerator,
	AnswerJoiner,
	BranchJoiner,
	DocumentJoiner,
	StringJoiner,
	DocumentCleaner,
	DocumentSplitter,
	RecursiveSplitter,
	TextCleaner,
	CohereRanker,
	FastembedRanker,
	JinaRanker,
	LostInTheMiddleRanker,
	MetaFieldRanker,
	MetaFieldGroupingRanker,
	NvidiaRanker,
	TransformersSimilarityRanker,
	SentenceTransformersDiversityRanker,
	ExtractiveReader,
	AstraEmbeddingRetriever,
	ChromaEmbeddingRetriever,
	ChromaQueryTextRetriever,
	ElasticsearchEmbeddingRetriever,
	ElasticsearchBM25Retriever,
	InMemoryBM25Retriever,
	InMemoryEmbeddingRetriever,
	FilterRetriever,
	MongoDBAtlasEmbeddingRetriever,
	OpenSearchBM25Retriever,
	OpenSearchEmbeddingRetriever,
	PgvectorEmbeddingRetriever,
	PgvectorKeywordRetriever,
	PineconeEmbeddingRetriever,
	QdrantEmbeddingRetriever,
	QdrantSparseEmbeddingRetriever,
	QdrantHybridRetriever,
	SentenceWindowRetriever,
	SnowflakeTableRetriever,
	WeaviateBM25Retriever,
	WeaviateEmbeddingRetriever,
	ConditionalRouter,
	FileTypeRouter,
	MetadataRouter,
	TextLanguageRouter,
	TransformersTextRouter,
	TransformersZeroShotTextRouter,
	TopPSampler,
	ToolInvoker,
	JsonSchemaValidator,
	SearchApiWebSearch,
	SerperDevWebSearch,
	DocumentWriter
}

enum DataType {
	None,	
	Any,
	ArgDict,
	Bool,
	DocStore,
	Document,
	DocumentList,
	Embedding,
	EmbeddingList,
	EmbeddedDocument,
	EmbeddedDocumentList,
	Int,
	PathOrByteStreamList,
	PathList,
	ApiKey,
	PlainString,
	PlainStringList,
	GeneratedAnswer,
	GeneratedAnswerList,
	ChatTemplate,
	ChatMessageList,
	Prompt,
	ModelName,
	URL,
	URLList,
	OpenAPISpec,
	ServiceCredentials,
	RawAzureResponse,
	JqFilterString,
	OpenAIFunctionDef,
	TypeAlias,
	JinjaTemplateString,
	MetaDict,
	MetaDictList,
	ScoreDict,
	ScoreDictList,
	DeepEvalMetric,
	DeepEvalResults,
	PredictedAnswers,
	StringOrMessageList,
	APIRoute,
	ChatMessage,
	APIResponse,
}

var TypeColors:Dictionary
func _init()-> void:
	TypeColors= {
		"None": Color.WHITE,
		"Any": Color.OLIVE,
		"ArgDict": Color.DODGER_BLUE,
		"BoolFalse": Color.BLACK,
		"BoolTrue": Color.WHITE,
		"DocStore": Color.DIM_GRAY,
		"Document": Color.BLUE_VIOLET,
		"DocumentList": Color.DARK_ORCHID,
		"Embedding": Color.CHOCOLATE,
		"EmbeddingList": Color.INDIAN_RED,
		"EmbeddedDocument": Color.FUCHSIA,
		"EmbeddedDocumentList": Color.DARK_MAGENTA,
		"Int": Color.CRIMSON,
		"PathOrByteStreamList": Color.CHARTREUSE,
		"PathList": Color.DARK_GREEN,
		"ApiKey": Color.FIREBRICK,
		"PlainString": Color.BLUE,
		"PlainStringList": Color.DARK_BLUE,
		"GeneratedAnswer": Color.CYAN,
		"GeneratedAnswerList": Color.DARK_CYAN,
		"ChatTemplate": Color.CORNFLOWER_BLUE,
		"ChatMessageList": Color.DARK_SLATE_BLUE,
		"Prompt": Color.DARK_SEA_GREEN,
		"ModelName": Color.DARK_OLIVE_GREEN,
		"URL": Color.DARK_SLATE_GRAY,
		"URLList": Color.MEDIUM_PURPLE,
		"OpenAPISpec": Color.DARK_TURQUOISE,
		"TypeAlias": Color.DARK_ORANGE,
		"ServiceCredentials": Color.DARK_RED,
		"RawAzureResponse": Color.DARK_ORANGE,
		"JqFilterString": Color.FOREST_GREEN,
		"OpenAIFunctionDef": Color.BURLYWOOD,
		"JinjaTemplateString": Color.CORAL,
		"MetaDict": Color.BROWN,
		"MetaDictList": Color.DARK_KHAKI,
		"ScoreDict": Color.DARK_GOLDENROD,
		"ScoreDictList":Color.GOLDENROD,
		"DeepEvalMetric": Color.DEEP_PINK,
		"DeepEvalResults": Color.DARK_SALMON,
		"PredictedAnswers": Color.DEEP_SKY_BLUE,
		"StringOrMessageList": Color.AQUA,
		"APIRoute": Color.MEDIUM_SEA_GREEN,
		"ChatMessage": Color.STEEL_BLUE,
		"APIResponse": Color.REBECCA_PURPLE
	}
